// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dapccqrrpnctsyunmszx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcGNjcXJycG5jdHN5dW5tc3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0Nzc1MDMsImV4cCI6MjA3MTA1MzUwM30.v5TmNQ1uMcaBx3BGpfULoUCHNCVWWXpiMU3Ihp7ofqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});